         Create a new array of 2*5 uints, filled with 6.
                               

In [3]:
import numpy as np

np.full((2, 5), 6, dtype=np.uint)



array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

In [6]:
np.random.rand (5,5)

array([[0.74151728, 0.88962718, 0.88989109, 0.32328566, 0.61191837],
       [0.2664467 , 0.54141754, 0.42929588, 0.5526399 , 0.60010368],
       [0.92605487, 0.28154751, 0.37870467, 0.64561903, 0.05782402],
       [0.14377068, 0.26735907, 0.50832873, 0.82741922, 0.54118524],
       [0.63520756, 0.7133214 , 0.65940605, 0.5368304 , 0.42477964]])

In [9]:
import numpy as np

arr = np.random.randint(1, 1000, 10)
print(arr)


[972 845 652 177 494 319 492 537 784 148]


NameError: name 'ranar' is not defined