      NAME/ MOHAMED HAZEM FAHMY AHMED
                   

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros


In [2]:
zeros_array = np.zeros(10)
print(repr(zeros_array))



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


#### Create an array of 10 ones

In [3]:
onse_array =np.ones(10)
print(repr(onse_array))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


#### Create an array of 10 fives


In [4]:
fives_array=np.ones(10)*5
print(repr(fives_array))

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


#### Create an array of the integers from 10 to 50


In [5]:

array_10_to_50 = np.arange(10, 51)
print(repr(array_10_to_50))


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
